/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Userbank;

/**
 *
 * @author David Darío Del Prado González
 */
public class Frame extends javax.swing.JFrame
{
    //Create the panels
    private Start startView;
    private Play playView;
    private Menu menuView;
    private GlobalStats globalStatsView;
    private UserStats userStatsView;
    
    //Create the userbank
    private Userbank userbank;

    /**
     * Creates new form Frame
     */
    public Frame()
    {
        initComponents();
        
        //Instantiate the panels
        startView   = new Start();
        playView    = new Play();
        menuView    = new Menu();
        globalStatsView = new GlobalStats();
        userStatsView   = new UserStats();
        
        //Set panels as cards for the layout
        this.getContentPane().add(startView);
        this.getContentPane().add(playView);
        this.getContentPane().add(menuView);
        this.getContentPane().add(globalStatsView);
        this.getContentPane().add(userStatsView);
    }
    
    public Frame(Userbank userbank)
    {
        this();
        
        //Reference the userbank
        this.userbank = userbank;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
