/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;




/**
 *
 * @author David Darío Del Prado González
 */
public class Play extends javax.swing.JPanel
{
    /**
     * Sent to the controller to let it know whether the user had already resolved
     * an operation or not.
     */
    private boolean isFirstOperation = true;
    
    /**
     * The frame that contains this panel, and acts as a controller to it.
     */
    private Frame controller;
    
    /**
     * Timer for bonus points. Also lets the user see how much time he has before
     * he gets no bonus.
     */
    private Timer timer;
    
    /**
     * Fired every second to update the label timer.
     */
    ActionListener updater;
        
    /**
     * Creates new form Play
     */
    public Play()
    {
        initComponents();
        
        //Initiate the timer and it's listener
        initTimer();
    }

    public Play(Frame controller)
    {
        this();
        
        //Reference the frame as the controller
        this.controller = controller; 
    }
    
    /**
     * Plots the operands and operation for the user to solve. Also, clears the
     * answer textfield.
     * @param data 3 position <ii>String</ii> array containing the operands and operation.
     * The order is operand1, operation and operand2.
     */
    public void plotOperation(String[] data)
    {
        //Set the labels with the data
        lblOperand1.setText(data[0]);
        lblOperation.setText(data[1]);
        lblOperand2.setText(data[2]);
        
        //Clear the answer TextField and the timer label
        txtResult.setText("");
        lblTimer.setText("30");
        
        //Start the Timer
        timer.start();
    }
    
    /**
     * Initiates the timer
     */
    private void initTimer()
    {
        updater = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e)
            {
                //Get aux variable to check if the label is 0 already
                int aux = Integer.parseInt(lblTimer.getText()) - 1;
                
                //If the label is not zero, update the label to show one second less
                if (aux >= 0)
                {
                    lblTimer.setText(String.valueOf(aux));
                }
            }            
        };
        
        //Set the timer to work with the above updater
        timer = new Timer(1000, updater);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        lblTitle = new javax.swing.JLabel();
        lblOperand1 = new javax.swing.JLabel();
        lblOperation = new javax.swing.JLabel();
        lblOperand2 = new javax.swing.JLabel();
        txtResult = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        lblTimer = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        lblTitle.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        lblTitle.setText("Calcula");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 50;
        add(lblTitle, gridBagConstraints);

        lblOperand1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblOperand1.setText("Operand1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(lblOperand1, gridBagConstraints);

        lblOperation.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblOperation.setText("+");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 50;
        add(lblOperation, gridBagConstraints);

        lblOperand2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblOperand2.setText("Operand2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(lblOperand2, gridBagConstraints);

        txtResult.setText("jTextField1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(txtResult, gridBagConstraints);

        btnSend.setText("Enviar");
        btnSend.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSendActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(btnSend, gridBagConstraints);

        lblTimer.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(lblTimer, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSendActionPerformed
    {//GEN-HEADEREND:event_btnSendActionPerformed
        // Stop the timer
        timer.stop();
        
        // TODO: User input validation - Maybe a DocumentListener?
        controller.checkOperation(Integer.parseInt(txtResult.getText()), Integer.parseInt(lblTimer.getText()), isFirstOperation);
        
        isFirstOperation = false;
    }//GEN-LAST:event_btnSendActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel lblOperand1;
    private javax.swing.JLabel lblOperand2;
    private javax.swing.JLabel lblOperation;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables

    public void setIsFirstOperation(boolean isFirstOperation)
    {
        this.isFirstOperation = isFirstOperation;
    }


    
}
