/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author David
 */
public class Start extends javax.swing.JPanel
{

    /**
     * Creates new form Inicio
     */
    public Start()
    {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        btnStart = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        btnStart.setText("Entrar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.weighty = 0.5;
        add(btnStart, gridBagConstraints);

        txtName.setText("Nombre");
        txtName.setToolTipText("");
        txtName.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                txtNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                txtNameFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 1;
        add(txtName, gridBagConstraints);

        lblTitle.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        lblTitle.setText("Reto Matemático");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weighty = 1.0;
        add(lblTitle, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_txtNameFocusGained
    {//GEN-HEADEREND:event_txtNameFocusGained
        if (txtName.getText().equalsIgnoreCase("Nombre"))
	{
	    txtName.setText("");
	}
    }//GEN-LAST:event_txtNameFocusGained

    private void txtNameFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_txtNameFocusLost
    {//GEN-HEADEREND:event_txtNameFocusLost
        if (txtName.getText().equalsIgnoreCase(""))
	{
	    txtName.setText("Nombre");
	}
    }//GEN-LAST:event_txtNameFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
